export const ceremonyContent = {
  heroTitle: 'Welcome Little Miracle',
  heroSubtitle: 'A Precious Gift From God',
  startButton: 'Begin the Blessing Journey',
  fatherName: "Dineshkumar",
  motherName: "Sutharsana",
  parentMessage: 'With hearts full of love and gratitude, we welcome the newest blessing in our family.',
  birthDetails: {
    date: '25  April  2026',
    time: '03.54 PM',
    place: 'Kilinochchi',
  },
  birthMessage: 'A beautiful soul entered our lives and filled our hearts with endless joy.',
  blessings: [
    'God has blessed us with a beautiful child.',
    'Every child is a gift from heaven.',
    'May this little one be guided by faith, love, and happiness.',
    'May God’s grace shine upon him forever.',
  ],
  revealPrompt: 'A special name has been chosen for this precious blessing...',
  revealButton: 'Reveal the Journey',
  babyName: 'Sankavi Jude',
  revealBlessing: 'May God bless you with a life filled with happiness, health, wisdom, and endless love.',
  finalTitle: 'Thank you for being part of this special moment.',
  finalSubtitle: 'Please keep our little prince in your prayers and blessings.',
  finalPhotoLabel: 'Our Little Prince',
  audioSource: 'birthday-song.mp3',
  videoSource: 'birthday-video-new.mp4',
}
